### ISSUE TITLE
Exception on snapshot change

### ISSUE THREAD

**Issue by soerendomroes** [kieler/vscode#11]
Sometimes a NPE or ConcurrentModificationException occurs when displaying a diagram for a snapshot (click on processor after compilation).

This does not seem to be a race condition and we are not sure why this happens, however, we want to investigate this.

**Comment by soerendomroes** [comment]
@NiklasRentzCAU I remember that you claimed to have fixed this, can you link the PR and close this?

**Comment by NiklasRentzCAU** [comment]
Core problem from other repository as described in kieler/klighd#121, fixed with kieler/klighd#131.
