### ISSUE TITLE
Introduce scaling to SVG in KIELER Visualization to fit the model in the view

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/vscode#35]
When testing for example the KIELER Visuaualization with the Elevator example, the SVG in the opened Browser is fit to the width and not the height of the browser, causing a scroll wheel to appear. Expected behavior would fit the SVG into the browser window so that everything is visible.

**Comment by soerendomroes** [comment]
See https://git.informatik.uni-kiel.de/ag-rtsys/kieler/models-private/-/merge_requests/8
